from django.contrib import admin
from django.urls import path

from videosurveillance_app import views

urlpatterns = [
    path('', views.login, name="login"),
    path('admin_home', views.admin_home, name="admin_home"),
    path('manage_security', views.manage_security, name="manage_security"),
    path('searchsecurity', views.searchsecurity, name="searchsecurity"),
    path('delete_security/<int:id>', views.delete_security, name="delete_security"),
    path('add_security', views.add_security, name="add_security"),
    path('addsecuritycode', views.addsecuritycode, name="addsecuritycode"),
    path('assign_work1/<int:id>', views.assign_work1, name="assign_work1"),
    path('add_assignworkcode', views.add_assignworkcode, name="add_assignworkcode"),
    path('assign_work2', views.assign_work2, name="assign_work2"),
    path('view_report', views.view_report, name="view_report"),
    path('view_feedback', views.view_feedback, name="view_feedback"),
    path('view_complaint', views.view_complaint, name="view_complaint"),
    path('send_reply/<int:id>', views.send_reply, name="send_reply"),
    path('sdrply', views.sdrply, name="sdrply"),
    path('add_camera1', views.add_camera1, name="add_camera1"),
    path('delete_camera/<int:id>', views.delete_camera, name="delete_camera"),
    path('add_camera2', views.add_camera2, name="add_camera2"),
    path('add_cameracode', views.add_cameracode, name="add_cameracode"),
    path('view_notification', views.view_notification, name="view_notification"),
    path('security_home', views.security_home, name="security_home"),
    path('viewassign_work', views.viewassign_work, name="viewassign_work"),
    path('updatework_status/<int:id>', views.updatework_status, name="updatework_status"),
    path('add_report/<int:id>', views.add_report, name="add_report"),
    path('add_reportcode', views.add_reportcode, name="add_reportcode"),
    path('send_feedback', views.send_feedback, name="send_feedback"),
    path('sdfeedback', views.sdfeedback, name="sdfeedback"),
    path('view_reply', views.view_reply, name="view_reply"),
    path('send_complaint', views.send_complaint, name="send_complaint"),
    path('sdcmpt', views.sdcmpt, name="sdcmpt"),
    path('camera_info', views.camera_info, name="camera_info"),
    path('view_alert', views.view_alert, name="view_alert"),
    path('logincode', views.logincode, name="logincode"),
    path('updt', views.updt, name="updt"),
    path('edit_security/<int:id>', views.edit_security, name="edit_security"),
    path('editsecurity_code', views.editsecurity_code, name="editsecurity_code"),
    path('searchcomplaint', views.searchcomplaint, name="searchcomplaint"),
    path('searchreply', views.searchreply, name="searchreply"),
    path('insertEmotions/<str:emo>/<int:camid>/<str:img>', views.insertEmotions, name="insertEmotions"),
    path('view_emotion', views.view_emotion, name="view_emotion"),
    path('logout', views.logout, name="logout"),
]
